[build]
builder = "dockerfile"
dockerfilePath = "Proyecto_Zetta.Server/Dockerfile"

[deploy]
startCommand = "dotnet Proyecto_Zetta.Server.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
