FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ../Proyecto_Zetta.Server/Proyecto_Zetta.Server.csproj ./Proyecto_Zetta.Server/
RUN dotnet restore ./Proyecto_Zetta.Server/Proyecto_Zetta.Server.csproj

# Agregar más pasos según sea necesario
